### ISSUE TITLE
After several transactions some nodes get out of sync.

### ISSUE THREAD

**Issue by baranbaygan** [mosaicnetworks/babble#16] opened 2018-01-09 20:30 UTC
How to reproduce: 

-start 4 nodes
-send transactions to 1 of nodes
-after 10 -20 transactions 1 or 2 nodes might show the consensus transaction count one less than others

Also this happened: (copied from watch.sh)

consensus_events:1400 consensus_transactions:**35** events_per_second:0.00 id:2 last_consensus_round:116 num_peers:3 round_events:12 rounds_per_second:0.00 state:Babbling sync_rate:1.00 **transaction_pool:35 undetermined_events:23**

consensus_events:1378 consensus_transactions:**34** events_per_second:0.00 id:0 last_consensus_round:114 num_peers:3 round_events:13 rounds_per_second:0.00 state:Babbling sync_rate:1.00 transaction_pool:0 undetermined_events:32

consensus_events:1400 consensus_transactions:**35** events_per_second:0.00 id:1 last_consensus_round:116 num_peers:3 round_events:12 rounds_per_second:0.00 state:Babbling sync_rate:1.00 transaction_pool:0 undetermined_events:23

consensus_events:1400 consensus_transactions:**35** events_per_second:0.00 id:3 last_consensus_round:116 num_peers:3 round_events:12 rounds_per_second:0.00 state:Babbling sync_rate:1.00 transaction_pool:0 undetermined_events:25

network doesn't accept any transactions any more. All tx stay in tx pool.

**Comment by arrivets** [comment] 2018-01-09 21:39
I cannot seem to reproduce it.

I can send 1000 tx to the same node and they all get committed very quick (with 4 nodes)
For this, I am using the `make bombard nodes=1 txs=1000` in the docker demo.

May I ask how you are submitting the transactions?

Do you see any errors in the logs? ( if you are using docker, run docker logs node2)

Thanks

**Comment by baranbaygan** [comment] 2018-01-10 07:48
It seems like it happens when 

--store=badger

with inmem storage I couldn't reproduce it either.  Trying further.

**Comment by baranbaygan** [comment] 2018-01-10 08:49
--store=badger
also
bombard.sh 1 3   (not 1000, but multiple times called from console. It can be reproduced more easily)

**Comment by baranbaygan** [comment] 2018-01-10 08:57
<img width="1604" alt="screen shot 2018-01-10 at 11 56 02" src="https://user-images.githubusercontent.com/384313/34763774-544dd3ee-f5fd-11e7-8872-531dd526b7bc.png">

**Comment by arrivets** [comment] 2018-01-10 10:36
Ok thanks for the logs, that was helpfull.

There is something interesting here (node.go, commit function):
```
for _, ev := range events {
		for _, tx := range ev.Transactions() {
			if err := n.proxy.CommitTx(tx); err != nil {
				return err
			}
		}
}
```
When the node fails to commit a Transaction, it abandons completely and stops committing the rest of the transactions that were past to it in this function call. We can see from the logs that this is happening to the  node with id 2 ("App returned false to CommitTx")

So that definitely needs to be fixed.

However it does not completely explain why the node stops accepting transactions.

In this case it would be helpful to see the logs of node2 (that is the name of the docker container but the id of the node - in the hashgraph - is 0)

**Comment by arrivets** [comment] 2018-01-10 10:37
I guess an extra step to reproduce the issue is to create an app that returns an error to some CommitTx calls.
With the dummy app I still don't see it happening.

**Comment by baranbaygan** [comment] 2018-01-10 11:39
When returning true to CommitTx same thing happened. It almost always happens when badger is used instead of inmem. I don't know how that is different.

<img width="1606" alt="screen shot 2018-01-10 at 14 30 22" src="https://user-images.githubusercontent.com/384313/34770687-d8cb6ea0-f612-11e7-8ca7-1016bef68c7a.png">

Logs for all 4 nodes:

<img width="1676" alt="screen shot 2018-01-10 at 14 35 42" src="https://user-images.githubusercontent.com/384313/34770957-e49b145a-f613-11e7-96c2-db04dfb259ef.png">

**Comment by arrivets** [comment] 2018-01-10 13:03
Do you see this also with the golang dummy app? I see you are using your own nodejs app.

**Comment by baranbaygan** [comment] 2018-01-10 14:13
With golang dummy app:

<img width="541" alt="screen shot 2018-01-10 at 17 08 36" src="https://user-images.githubusercontent.com/384313/34776785-02eddec8-f629-11e7-89c7-ad3146a711b2.png">

How can it be any different anyway? nodejs or golang? In the end they just receive commit messages and what they return is not taken into account by babble. Actually it is the same if I don't run a dummy app at all because I am sending submitTx from bombard.sh. 

Can it be the case this stats service is returning something wrong? Maybe babble works correctly but stats service is returning invalid numbers?

**Comment by arrivets** [comment] 2018-01-10 15:23
Actually what the app returns **is** taken under account by Babble. If the response contains an error, the node breaks out of the commit loop as I indicated higher. But you are right it seems to be a separate issue.

I don't think this symptom is related to the stats service. 

The fact that the issue only occurs with the --store=badger flag is quite meaningful. 

I would need to see the entire log file for the node that falls behind.

**Closed as completed** 2018-08-14 08:16 UTC
